version: '3'

services:
    client-host:
        image: versioneer/client-host
        build: 
            context: ${CLIENTHOST_PATH}
        ports:
            - 5000:80
        environment: 
            - ASPNETCORE_ENVIRONMENT=${CLIENTHOST_ASPNETENV}